### ISSUE TITLE
NOOP pattern for performance

### ISSUE THREAD

**Issue by bd82** [mindoro/mindoro#6]
Something you could try:

Lets look at this example.
```javascript
 if (this.flags & Flags.OptionsRaw) {
    this.tokenRaw = this.rawValue(start, this.index);
}
```

Lets assume OptionsRaw flag is decided before parsing (once).
However the "IF" will still get evaluated each and every time this code is executed, which costs some CPU cycles.

instead we can use something like:

```javascript
// empty function, if this is inlined it disappears and no runtime cost.
function NOOP () {}

// real implementation, should be inlined and provide identical performance
// to writing this directly as the function invocation will disappear.
parser.assignTokenRaw = function assignTokenRaw() {
   this.tokenRaw = this.rawValue(start, this.index);
}

if (Flags.OptionsRaw === false) {
   parser.assignTokenRaw  = NOOP
}


// some usage of the assignTokenRaw
// either it will be inlined as NOOP so actually as "EMPTY TEXT".
// or it will be inlined as the original code with the assignment but without the function call.
this.assignTokenRaw()
```

**Comment by KFlash** [comment]
Hi. Thanks for this. I will look into it. I made a couple of changes, but ATM I'm doing some heavy refactoring so my brain is somewhere else. I will push my changes to the dev branch shortly.

**Comment by KFlash** [comment]
@bd82 Another option is to inline this into the parser code inside `createLiteral` and have a common literal node for creating literals including booleans and null. This will also catch a few bugs I'm aware of :)

**Comment by KFlash** [comment]
@bd82 Closing this now as this is taken care of, and a permanent solution will land within 7 - 8 days.
